version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.0
      - image: cimg/postgres:14.4
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: postgres
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          name: Restore RubyGems Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: '"browser-tools" によるインストールのチェック'
          command: |
            which google-chrome
            google-chrome --version

            which chromedriver
            chromedriver --version
      - run:
          name: 必要なパッケージをインストールする
          command: |
            sudo apt install fonts-migmix
      - run:
          name: Node.js をインストールする
          # https://github.com/nodesource/distributions/blob/master/README.md#debmanual
          command: |
            curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
            sudo apt install -y nodejs
            echo 'Node.js のバージョンは、'
            node -v
            echo 'Node.js がインストールされている場所は、'
            which node
      - run:
          name: Yarn をインストールする
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt update -y && sudo apt install yarn -y
            echo 'Yarn のバージョンは、'
            yarn -v
            echo 'Yarn がインストールされている場所は、'
            which yarn
      - run:
          name: $ bundle install を行う
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          name: Save RubyGems Cache
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: データベースのセットアップ
          command: |
            bin/rails db:prepare
      - run:
          name: RSpec を実行する
          command: |
            bundle exec rspec
      - store_artifacts:
          path: ~/project/tmp/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/project/tmp/capybara
          destination: capybara
